config/routes.rb
ArcserverDemo::Application.routes.draw do
  resources :homes do
    collection do
      get 'service_layers'
    end  
  end  

  get "service_layers" => "homes#service_layers", :as => "service_layers"

  get "example" => "homes#example", :as => "example"

  get "open_info_window_immediately" => "homes#open_info_window_immediately", as: :open_info_window_immediately

 root :to => 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    
  end
  
  def service_layers
    render  :layout => false
  end  

  def example
  end
  
  def open_info_window_immediately
   render  :layout => false
  end  
  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/example.html.erb
    <style>
      html, body, #map {
        padding:0;
        margin:0;
        height:100%;
      }
    </style>

    <script>var dojoConfig = {parseOnLoad: true};</script>
    <script src="http://js.arcgis.com/3.9/"></script>
    <script>
      dojo.require("esri.map");
      dojo.require("dijit.layout.BorderContainer");
      dojo.require("dijit.layout.ContentPane");
      dojo.require("esri/layers/DynamicMapServiceLayer");
      dojo.require("esri/tasks/QueryTask");
      dojo.require("esri/tasks/query");
      dojo.require("esri/symbols/SimpleMarkerSymbol");
      dojo.require("esri/InfoTemplate");
      dojo.require("dojo/_base/Color");
      dojo.require("dojo/domReady!");
      dojo.require("esri/tasks/FeatureSet");
      dojo.require("dojo/dom");
      dojo.require("dojo/on");
       
      function init() {
  //create map and add layer
  map = new esri.Map("mapDiv");
  var layer = new esri.layers.ArcGISDynamicMapServiceLayer("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StatesCitiesRivers_USA/MapServer");
  map.addLayer(layer);

  //initialize query task
  queryTask = new esri.tasks.QueryTask("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StatesCitiesRivers_USA/MapServer/0");

  //initialize query
  query = new esri.tasks.Query();
  query.returnGeometry = true;
  query.outFields = ["CITY_NAME", "STATE_NAME", "POP1990"];

  //initialize InfoTemplate
  infoTemplate = new esri.InfoTemplate("${CITY_NAME}", "Name : ${CITY_NAME}<br/> State : ${STATE_NAME}<br />Population : ${POP1990}");

  //create symbol for selected features
  symbol = new esri.symbol.SimpleMarkerSymbol();
  symbol.setStyle(esri.symbol.SimpleMarkerSymbol.STYLE_SQUARE);
  symbol.setSize(10);
  symbol.setColor(new dojo.Color([255,123,0,0.5]));
}

 function executeQueryTask(population) {
    //set query based on what user typed in for population;
    query.where = "POP04 > " + population;

    //execute query
    queryTask.execute(query,showResults());
  }

  function showResults(featureSet) {
    //remove all graphics on the maps graphics layer
    map.graphics.clear();

    //Performance enhancer - assign featureSet array to a single variable.
    var resultFeatures = featureSet.features;

    //Loop through each feature returned
    for (var i=0, il=resultFeatures.length; i<il; i++) {
      alert(resultFeatures.length);
      //Get the current feature from the featureSet.
      //Feature is a graphic
      var graphic = resultFeatures[i];
      graphic.setSymbol(symbol);

      //Set the infoTemplate.
      graphic.setInfoTemplate(infoTemplate);

      //Add graphic to the map graphics layer.
      map.graphics.add(graphic);
    }
  }
         dojo.ready(init);
          
    </script>
  
       <br/>
    US city population greater than : <input type="text" id="population" value="500000" />
    <input type="button" value="Get Details" onclick="executeQueryTask(dojo.byId('population').value);" />

    <div id="mapDiv" style="width:600px; height:600px; border:1px solid #000;"></div>
    Click on a city once it's highlighted to get an InfoWindow.

app/views/homes/index.html.erb
    <style>
      html, body, #map {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
      }
      #search {
        display: block;
        position: absolute;
        z-index: 3;
        top: 20px;
        left: 75px;
      }
      .spotlight {
        z-index:-1;
        position:absolute;
        left:50%;
        top:50%;
        border-radius:50%;
        opacity:0;
        box-shadow:
        inset rgba(0,0,0,0.25) 0px 0px 20px 20px,
        rgba(0,0,0,0.25) 0px 0px 0px 1000px;
        transition:all 1000ms;
        -moz-transition:all 1000ms;
        -webkit-transition:all 1000ms;
      }
      .spotlight-active {
        z-index:2;
        opacity:1;
      }
    </style>
    
    <script src="http://js.arcgis.com/3.9/"></script>
    <script>
      require([
        "esri/map",
        "esri/dijit/Geocoder",

        "esri/graphic",
        "esri/symbols/SimpleMarkerSymbol",
        "esri/geometry/screenUtils",

        "dojo/dom",
        "dojo/dom-construct",
        "dojo/query",
        "dojo/_base/Color",

        "dojo/domReady!"
      ], function(
        Map, Geocoder,
        Graphic, SimpleMarkerSymbol, screenUtils,
        dom, domConstruct, query, Color
      ) { 
        // create a map and instance of the geocoder widget here
        var map = new Map("map", {
          basemap: "topo", 
          center: [ 78, 13 ], 
          zoom: 10
        });
        var geocoder =  new Geocoder({
          arcgisGeocoder: {
            placeholder: "Find a place"
          }, 
          autoComplete: true,
          map: map
        }, dom.byId("search"));

        map.on("load", enableSpotlight);

        geocoder.on("select", showLocation);
        geocoder.on("clear", removeSpotlight);

        function showLocation(evt) {
          map.graphics.clear();
          var point = evt.result.feature.geometry;
          var symbol = new SimpleMarkerSymbol().setStyle(
            SimpleMarkerSymbol.STYLE_SQUARE).setColor(
            new Color([255,0,0,0.5])
          );
          var graphic = new Graphic(point, symbol);
          map.graphics.add(graphic);

          map.infoWindow.setTitle("Search Result");
          map.infoWindow.setContent(evt.result.name);
          map.infoWindow.show(evt.result.feature.geometry);

          var spotlight = map.on("extent-change", function(extentChange) {
            var geom = screenUtils.toScreenGeometry(map.extent, map.width, map.height, extentChange.extent);
            var width = geom.xmax - geom.xmin;
            var height = geom.ymin - geom.ymax;

            var max = height;
            if ( width > height ) {
                max = width;
            }

            var margin = '-' + Math.floor(max/2) + 'px 0 0 -' + Math.floor(max/2) + 'px';

            query(".spotlight").addClass("spotlight-active").style({
              width: max + "px",
              height: max + "px",
              margin: margin
            });
            spotlight.remove();
          });
        }

        function enableSpotlight() {
          var html = "<div id='spotlight' class='spotlight'></div>"
          domConstruct.place(html, dom.byId("map_container"), "first");
        }

        function removeSpotlight() {
          query(".spotlight").removeClass("spotlight-active");
          map.infoWindow.hide();
          map.graphics.clear();
        }
      });
    </script>

    <div id="search"></div>
    <div id="map"></div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/open_info_window_immediately.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!--The viewport meta tag is used to improve the presentation and behavior of the samples 
      on iOS devices-->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">
    <title>QueryTask with geometry, queries with multiple results at the same location are displayed in an InfoWindow</title>

    <link rel="stylesheet" href="http://js.arcgis.com/3.9/js/dojo/dijit/themes/claro/claro.css">
    <link rel="stylesheet" href="http://js.arcgis.com/3.9/js/esri/css/esri.css">
    
    <script src="http://js.arcgis.com/3.9/"></script>
    <script>
      dojo.require("esri.map");
      dojo.require("esri.tasks.query");

      var map, queryTask, query;
      var featureSet;

      // require(["esri/config"], function(esriConfig) { 
      //     esriConfig.defaults.io.proxyUrl = "http://sampleserver1.arcgisonline.com"
      //     esriConfig.defaults.io.alwaysUseProxy = false;
      //  });

      function init() {
        var startExtent = new esri.geometry.Extent({"xmin":-11207421,"ymin":4469708,"xmax":-10718224,"ymax":4836606,"spatialReference":{"wkid":102100}} );
        map = new esri.Map("mapDiv", {
          basemap: "satellite",
          center: [-98.481, 38.52],
          zoom: 8
        });

        //create and add new layer
        var dynamicLayer = new esri.layers.ArcGISDynamicMapServiceLayer("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Petroleum/KGS_OilGasFields_Kansas/MapServer");
        map.addLayer(dynamicLayer);

        //Listen for click event on the map, when the user clicks on the map call executeQueryTask function.
        dojo.connect(map, "onClick", executeQueryTask);

        //Listent for infoWindow onHide event
        dojo.connect(map.infoWindow, "onHide", function() {map.graphics.clear();});

        //build query task
        queryTask = new esri.tasks.QueryTask("http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Petroleum/KGS_OilGasFields_Kansas/MapServer/0");

        //Can listen for onComplete event to process results or can use the callback option in the queryTask.execute method.
        //dojo.connect(queryTask, "onComplete", showResults);

        //build query filter
        query = new esri.tasks.Query();
        query.outSpatialReference = {"wkid":102100};
        query.returnGeometry = true;
        query.outFields = ["FIELD_NAME", "FIELD_KID", "PROD_GAS", "PROD_OIL", "STATUS"];
      }

      function executeQueryTask(evt) {
        map.infoWindow.hide();
        map.graphics.clear();
        featureSet = null;

        //onClick event returns the evt point where the user clicked on the map.
        //This is contains the mapPoint (esri.geometry.point) and the screenPoint (pixel xy where the user clicked).
        //set query geometry = to evt.mapPoint Geometry
        query.geometry = evt.mapPoint;

        //Execute task and call showResults on completion
        queryTask.execute(query, function(fset) {
          if (fset.features.length === 1) {
            showFeature(fset.features[0],evt);
          } else if (fset.features.length !== 0) {
            showFeatureSet(fset,evt);
          }
        });
      }

      function showFeature(feature,evt) {
        map.graphics.clear();

        //set symbol
        var symbol = new esri.symbol.SimpleFillSymbol(esri.symbol.SimpleFillSymbol.STYLE_SOLID, new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID, new dojo.Color([255,0,0]), 2), new dojo.Color([255,255,0,0.5]));
        feature.setSymbol(symbol);

        //construct infowindow title and content
        var attr = feature.attributes;
        var title = attr.FIELD_NAME;
        var content = "Field ID : " + attr.FIELD_KID
                    + "<br />Produces Gas : " + attr.PROD_GAS
                    + "<br />Produces Oil : " + attr.PROD_OIL
                    + "<br />Status : " + attr.STATUS;
        map.graphics.add(feature);

        map.infoWindow.setTitle(title);
        map.infoWindow.setContent(content);

        (evt) ? map.infoWindow.show(evt.screenPoint,map.getInfoWindowAnchor(evt.screenPoint)) : null;
      }

      function showFeatureSet(fset,evt) {
        //remove all graphics on the maps graphics layer
        map.graphics.clear();
        var screenPoint = evt.screenPoint;

        featureSet = fset;

        var numFeatures = featureSet.features.length;

        //QueryTask returns a featureSet.  Loop through features in the featureSet and add them to the infowindow.
        var title = "You have selected " + numFeatures + " fields.";
        var content = "Please select desired field from the list below.<br />";

        for (var i=0; i<numFeatures; i++) {
          var graphic = featureSet.features[i];
          content = content + graphic.attributes.FIELD_NAME + " Field (<A href='#' onclick='showFeature(featureSet.features[" + i + "]);'>show</A>)<br/>";
        }

        map.infoWindow.setTitle(title);
        map.infoWindow.setContent(content);
        map.infoWindow.show(screenPoint,map.getInfoWindowAnchor(evt.screenPoint));
      }

      dojo.ready(init);
    </script>
  </head>
  <body class="claro">
    Click on a petrolueum field to get more info.  If mulitple fields are selected then you can select the field to display.
    <div id="mapDiv" style="width:800px; height:600px; border:1px solid #000;"></div>
  </body>
</html>
 
          

app/views/homes/service_layers.erb
    <style>
      html, body, #map {
        padding:0;
        margin:0;
        height:100%;
      }
    </style>

    <script>var dojoConfig = {parseOnLoad: true};</script>
    <script src="http://js.arcgis.com/3.9/"></script>
    <script>
      dojo.require("esri.map");
      dojo.require("dijit.layout.BorderContainer");
      dojo.require("dijit.layout.ContentPane");
      dojo.require("esri/layers/DynamicMapServiceLayer");
      dojo.require("esri/tasks/QueryTask");
      dojo.require("esri/tasks/query");
      dojo.require("esri/symbols/SimpleMarkerSymbol");
      dojo.require("esri/InfoTemplate");
      dojo.require("dojo/_base/Color");
      dojo.require("dojo/domReady!");
      dojo.require("esri/tasks/FeatureSet");
      dojo.require("dojo/dom");
      dojo.require("dojo/on");
       
      function init() {
        var customExtentAndSR = new esri.geometry.Extent(-12947200.702,3986037.689,-12927632.823,3996365.181, new esri.SpatialReference({"wkid":3857}));
        //create map with new custom spatial reference and extent.  The map will be in the Goode Homolosine Land projection
        var map = new esri.Map("map", { 
          extent: customExtentAndSR });
        //map service layer has a default spatial reference of 4326.
        var mapServiceLayer1 = new esri.layers.ArcGISDynamicMapServiceLayer("http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer");
        map.addLayer(mapServiceLayer1);
        var mapServiceLayer2 = new esri.layers.ArcGISDynamicMapServiceLayer("http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer");
        map.addLayer(mapServiceLayer2);
        var mapServiceLayer3 = new esri.layers.ArcGISDynamicMapServiceLayer("http://50.112.160.181:6080/arcgis/rest/services/demo/demo_gis_ms/MapServer");
        map.addLayer(mapServiceLayer3);


          //initialize query task
          var queryTask = new esri.tasks.QueryTask("http://50.112.160.181:6080/arcgis/rest/services/demo/demo_gis_ms/MapServer/8");

          //initialize query
          var query = new esri.tasks.Query();
          query.returnGeometry = false;
          query.outFields = ["facility id", "watertype", "subtypecode", "projectnumber", "lifecyclestatus", "material", "hyperlink", "pressurezone", "exteriorcoating", "liningtype", "pipeclass", "roughness", "diameter", "pressurerating", "comments", "installdate", "shape", "st_length", "objectid"];
          
          // query.geometry = evt.mapPoint;
          queryTask.execute(query, showResults());
          
            function showResults(featureSet) {
              alert(featureSet);
              alert("Hi");
              //remove all graphics on the maps graphics layer
              map.graphics.clear();

              //Performance enhancer - assign featureSet array to a single variable.
              var resultFeatures = featureSet.features;
              alert(resultFeatures.length)
              //Loop through each feature returned
              for (var i=0, il=resultFeatures.length; i<il; i++) {
                //Get the current feature from the featureSet.
                //Feature is a graphic
                alert(alertFeatures[i]);
                var graphic = resultFeatures[i];
                graphic.setSymbol(symbol);

                //Set the infoTemplate.
                graphic.setInfoTemplate(infoTemplate);

                //Add graphic to the map graphics layer.
                map.graphics.add(graphic);
              }
            };

          //initialize InfoTemplate
          infoTemplate = new esri.InfoTemplate(["${FACILITY ID}", "${WATERTYPE}", "${SUBTYPECODE}", "${PROJECTNUMBER}", "${LIFECYCLESTATUS}", "${MATERIAL}", "${HYPERLINK}", "${PRESSUREZONE}", "${EXTERIORCOATING}", "${LININGTYPE}", "${PIPECLASS}", "${ROUGHNESS}", "${DIAMETER}", "${PRESSURERATING}", "${COMMENTS}", "${INSTALLDATE}", "${SHAPE}", "${ST_LENGTH}", "${OBJECTID}"]);

          //create symbol for selected features
          symbol = new esri.symbol.SimpleMarkerSymbol();
          symbol.setStyle(esri.symbol.SimpleMarkerSymbol.STYLE_SQUARE);
          symbol.setSize(10);
          symbol.setColor(new dojo.Color([255,255,0,0.5]));
        
      }

         dojo.ready(init);
          
    </script>
  
       <div data-dojo-type="dijit.layout.BorderContainer" 
           data-dojo-props="design:'headline', gutters:false"
           style="width: 100%; height: 100%; margin: 0;">

         <div id="map" 
               data-dojo-type="dijit.layout.ContentPane" 
               data-dojo-props="region:'center'">
               <br/>
               </div>

       </div>

      

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArcGIS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://js.arcgis.com/3.9/js/esri/css/esri.css">
  <script src="http://js.arcgis.com/3.9/"></script>
</head>
<body >

<%= yield %>

</body>
</html>